version: 2.1
orbs:
    heroku: circleci/heroku@0.0.10.
executors:
    node:
        docker:
            - image: circleci/node:10
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - build
    jobs:
        build:
            executor: node
            steps:
                - checkout
                - run: npm install
                - run: npm install --prefix client
                - run: npm run build
        test:
            executor: node
            steps:
                - checkout
                - run: npm install
                - run: npm install --prefix client
                - run: npm run test
        heroku/deploy-via-git:
            requires:
                - build
            filters:
                branches:
                    only: master
