version: 2.1
orbs:
    heroku: circleci/heroku@0.0.10
executors:
    node:
        working_directory: ~/repo
        docker:
            - image: circleci/node:10
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - build
                requires:
                    - test 
            - heroku/deploy-via-git
                requires:
                    - build   
jobs:
    build:
        executor: node
        steps:
            - checkout
            - run: npm install  --no-package-lock
            - run: npm install --prefix client  --no-package-lock
            - run: npm run build
    test:
        executor: node
        steps:
            - checkout
            - run: npm install  --no-package-lock
            - run: npm install --prefix client  --no-package-lock
            - run: npm run test