version: 2.1
orbs:
    heroku: circleci/heroku@0.0.10
executors:
    node:
        working_directory: ~/repo
        docker:
            - image: circleci/node:10
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - build
            - heroku/deploy-via-git
jobs:
    build:
        steps:
            - checkout
            - run: npm install
            - run: npm install --prefix client
            - run: npm run build
    test:
        steps:
            - checkout
            - run: npm install
            - run: npm install --prefix client
            - run: npm run test