version: 2.1
orbs:
    heroku: circleci/heroku@0.0.10
    node: 'circleci/node:latest'
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - build
            - heroku/deploy-via-git
jobs:
    build:
        executor: node/default
        steps:
            - checkout
            - node/install-packages:
                cache-path: ~/project/node_modules
                override-ci-command: npm install
            - node/install-packages:
                cache-path: ~/project/client/node_modules
                override-ci-command: npm install --prefix client
            - run: npm run build
    test:
        executor: node/default
        steps:
            - checkout
            - node/install-packages:
                cache-path: ~/project/node_modules
                override-ci-command: npm install
            - node/install-packages:
                cache-path: ~/project/client/node_modules
                override-ci-command: npm install --prefix client
            - run: npm run test